### PR TITLE
Preferences restructured. New "Event filters" header introduced

### PR DESCRIPTION
**Pull request by yvolk**
New "Event filters" header introduced to allow further filtering enhancements.
Old "Events" header renamed to "Event details" - this is exactly what it is after removing "filters" from it!

Now it's much clearer to see, where we will put other proposed options like:
#151 Add ability to hide calendar events
#122 Show events that ended in past X hours (configurable)
and similar...

### CODE REVIEW

**Comment by mpost** [comment]
When updating the strings please make sure to also update the strings.xml file on crowdin.

**Comment by yvolk** [comment]
Now the widget with 
"Show days without events" turned on and
"Past events background color" looks like this:
dayswithoutevents

**Comment by yvolk** [comment]
@mpost Ok, please grant me permission at Crowdin.com to update files. I joined the https://crowdin.com/project/plusonelabs-calendar-widget project.

**Comment by mpost** [comment]
@yvolk You should now be a manager on the project. :)

Let me know if you need help finding your way around. Atm you just upload the the new strings.xml file in english and people will be able to contribute translations.

**Comment by yvolk** [comment]
@mpost Thank you, a while back I already noticed that you are using Crowdin.com for translation and arranged the same for [AndStatus](https://crowdin.com/project/andstatus), so I have some experience :-) 
BTW, you may be interested in using FB2 eBook format for a User Guide of Android application, [see this discussion](https://crowdin.com/project/andstatus/discussions/5).

**Comment by mpost** [comment]
@yvolk Good to see that you have experience.

Also pretty cool how so many translaters jumped in immediatly to translate the missing strings after your mail. :)

What i don't likw about crowdin is how they map to the android language codes. You always have to copy the content to the right strings.xml files by hand. None the less the service itself is pretty nice.

**Comment by yvolk** [comment]
@mpost Fo far I used only two-letters language codes for translations, so I didn't notice this problem in Crowdin.com. Maybe we can really rename in repository e.g. "values-bg" to "values-bg-rBG" and thus simplify our lifes?!

**Pull request merged**
